function  I=NewtonCotes(f,a,b,type)
%牛顿-科茨系列公式求函数f在区间[a,b]上的定积分
%函数名:f
%积分下限:a
%积分上限:b
%辛普森公式的类型:type(可取1,2,3)
%积分值:I
if nargin==4&&type==3
    eps=1e-4;
end

I=0;

switch type
    case 1,
        I=(b-a)/90*(7*subs(sym(f),findsym(sym(f)),a)+...
            32*subs(sym(f),findsym(sym(f)),(3*a+b)/4)+...
            12*subs(sym(f),findsym(sym(f)),(a+b)/2)+...
            32*subs(sym(f),findsym(sym(f)),(a+3*b)/4)+...
            7*subs(sym(f),findsym(sym(f)),b));
    case 2,
        I=(b-a)/288*(19*subs(sym(f),findsym(sym(f)),a)+...
            75*subs(sym(f),findsym(sym(f)),(4*a+b)/5)+...
            50*subs(sym(f),findsym(sym(f)),(3*a+2*b)/5)+...
            50*subs(sym(f),findsym(sym(f)),(2*a+3*b)/5)+...
            75*subs(sym(f),findsym(sym(f)),(a+4*b)/5)+...
            19*subs(sym(f),findsym(sym(f)),b));
    case 3,
        I=(b-a)/840*(41*subs(sym(f),findsym(sym(f)),a)+...
            216*subs(sym(f),findsym(sym(f)),(5*a+b)/6)+...
            27*subs(sym(f),findsym(sym(f)),(2*a+b)/3)+...
            272*subs(sym(f),findsym(sym(f)),(a+b)/2)+...
            27*subs(sym(f),findsym(sym(f)),(a+2*b)/3)+...
            216*subs(sym(f),findsym(sym(f)),(a+5*b)/6)+...
            41*subs(sym(f),findsym(sym(f)),b));
end
I=vpa(I,5);      